site:
  title: Architecting OpenShift Virtualization
  start_page: Red Hat OpenShift Virtualization - Architecting OpenShift Virtualization::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui