= Expand with Migration Factory

The Migration Factory phase describes how we do migration at scale and multiply the execution workstream.
Red Hat recommends the Migration Squad Model.
The Core Migration Team will consist of a Red Hat Program Manager, Lead Architect, Platform Consultant, and Automation Consultant alongside a core group of the financial company members, preferably from the O&I team.
There will be multiple Migration Squads, each led by an individual trained by the Core Migration Team, who will guide the VM owners through the process of migration.
Each Squad will be responsible for:

== Tasks

* Identify Workloads, Network, Storage
* Identify related Workloads such as Clusters, 3-tier applications, dependent microservices
* VM Migration
** Ansible Development
** Reevaluation of processes and automation based on pilot migrations
* ServiceNow Integration Workstream
** Provisioning Operations
** VM Control Operations (Day Two)
** Migration Self Service
* Strategize migration approach
** Acceptable Outage duration and window
** Notification List
** Preflight Checks
** Success Criteria

== Outputs

* Multiple Migration Plans executed
* Metrics Collected
** Speed
** Errors
** Outage times
* Identified opportunities for improvement
