= Virtualization Migration Assessment

The Virtualization Migration Assessment ensures that Red Hat’s knowledge of OpenShift (OCP), OpenShift Virtualization (OCP-Virt), Migration Toolkit for Virtualization (MTV) and other technologies are properly communicated and demonstrated to clients.

During this assessment, the financial company should clearly communicate its knowledge of their enterprise environment, their requirements, and their goals.

== Tasks

* The financial company provided an in-depth review of their current environment, problems with their current environment, and their desired future environment.
* Red Hat demoed OpenShift, OpenShift Virtualization, and the Migration Toolkit for Virtualization.
* Red Hat provided an in-depth review of the relevant technology and tools and proposed a High Level Design (HLD) to meet the financial company’s virtualization migration goals.

== Outputs
After the assessment was completed, the financial company was able to identify several key requirements for moving ahead with the migration.

* Near and long-term goals
* Proof of Technology (PoT) environment requirements
* Proposed Architecture and Bill of Materials for Pilot Phase
* Procurement estimates for Pilot infrastructure build

