= Technical OpenShift Virtualization Questions

The following questions will help you in finding the detailed information about current environment of the customer.

== General
* How many VMware clusters do you have running?
** Are they in multiple locations?
** How many hypervisors per cluster?
*** Are there any variations in hardware configurations across hypervisors within the same cluster(s)?
*** How many sockets per hypervisor?
* How many VMs are you running in your cluster(s)?
** What is the total number of virtual CPUs and RAM allocated to these VMs?
** What type of workloads are running in VMs today?
** What's the approximate percentage of VMs running on Windows and percentage of VMs running on RHEL?
** What type of software and software applications do you host in your environments? (COTS/GOTS/MOTS/In-house/other)
*** Specifically, could you provide examples of the most critical applications and their importance to your organization’s operations?
*** Would these applications need to be migrated hot or are cold migrations possible?
** Do you have any workloads requiring compute acceleration (rendering, AI/ML, remote 3D visualization) that would benefit from GPUs?
** Are you planning on migrating all of your VMs to a new platform?
*** (Follow-up) What is your timeline (if any) for completing this migration
*** (Follow-up) Do you foresee any potential challenges or roadblocks in achieving this e.g. people assets, skills gaps, security requirements, etc.?
* Are you leveraging any of the following VMware features?  If so please explain your use case.
** HA (High Availability)
** DRS (Distributed Resource Scheduling)
** VSAN (Software defined storage)
** NSX (Software defined networking)
** Distributed Switching
** Snapshots
** SRM (Site Recovery Manager)
** Aria Automation / VRealize

== Networking
* Networking Config
** How is networking currently configured in your VMware environment?
** Are there any specific network configs or VLANs that need to be replicated in the OpenShift Virtualization environment?
* Network Security
** What security measures are in place for network traffic within your VMware environment?
** Are there any specific firewall rules or network segmentation requirements that need to be replicated in OpenShift Virtualization?
* DNS/Name Resolution
** How is DNS and NR currently managed?
** Are there any additional or specific DNS configurations/requirements that need to be addressed in the OpenShift Virtualization env?
* Load Balancing/Service Discovery
** How are they currently doing it?
** Are there any additional or specific requirements for service discovery, external lb, routing, etc?
* Network Performance
** Does your org have any requirements for network performance and latency?
** Any performance-critical applications or workloads relying on low-latency networking?
* External Connectivity Requirements
** Any requirements for external connectivity for apps hosted in the OpenShift Virtualization env?
* Network Monitoring and Troubleshooting
** What tools or processes do you have in place for monitoring and troubleshooting your network?

== Storage
* What type of storage hardware is in use (vendor/model)? Netapp, Pure, Dell, HPE, etc
** Motivation for the question: Will this storage work with OCP?
*** Does it have a CSI Driver?
*** Does it work and is supported on OCP?
** Can you confirm if RWX storage is (or will be) available?  How is it (or will it be) provisioned? (Required for “OCP-V Live Migration” aka “vMotion”)
* What storage protocol are you using to present storage to your clusters (NFS, iSCSI, Direct Attached)? (Please provide configurations for each cluster if there are multiple clusters)
** Could you also elaborate on any performance and/or latency requirements for storage access?
* How much storage capacity is presented/consumed to your clusters? (Please provide configurations for each cluster if there are multiple clusters)
** Do you see this need increasing in the future?  Do you have storage hungry workloads planned?
* Is there any additional storage capacity for migration efforts?

== User Access and Authentication
* How are they currently managed in your vmware env
* Any specific requirements for user authentication, access control, SSO, etc.?

== Compliance and Governance
* Any regulatory compliance requirements/benchmarks that need to be considered/that customers are beholden to?

== Backup and DR
* What backup and disaster recovery solutions are you using today that we could potentially leverage in the new environment?
* What type of redundancy and fault tolerance mechanisms are currently in place?
** Application
** Storage
** Networking
** DR Cluster failover

== Training and Skill Development
* What is your team’s experience level with managing Kubernetes?
* Are there any existing training and/or certification initiatives for Kubernetes/OpenShift within their organization?
* Do/Will your IT teams require training or “upskilling” in Kubernetes (or more specifically OpenShift) and OpenShift Virtualization?

== Integration with Existing Systems:
* Are there any third-party systems, tools, and/or applications that need to integrate with OpenShift Virtualization (or your workloads running on OpenShift Virtualization)?  Please elaborate on each.

== Automation
* Image Provisioning and Configuration
** How are VM images currently provisioned and configured in your VMware env?
** Do you use tools like cloud-init or sysprep for image customization and configuration?
* Automated VM Provisioning
** Are there any requirements for automated VM provisioning and/or orchestration in the new OpenShift Virt environment?
** Do you have requirements for bulk deployment of VMs (such as deploying multiple  instances of the same VM template)??
*** What tools or processes are you currently using to accomplish this?
* GitOps and CI/CD Integration??
** Any plans (or expectations) to integrate GitOps principles or CI/CD pipelines into the management of your workloads/VMs in OpenShift Virtualization?

== Future Looking
* What is the timeline you are looking to have the migration started and what is your ideal completion time frame?
* Do you have a budget allocated for this migration effort?
* Are there plans to modernize any application into containers during the migration effort or shortly thereafter?
* Do you anticipate any long-term growth or expansion of your app portfolio that may impact storage, networking, etc. requirements beyond the initial migration phase?

